face_module:
  ros__parameters:
    core: face_core
    afferent: face_afferent
    face_afferent:
      topics: ["/image_raw"]
    efferent: face_efferent
    face_efferent:
      topics: ["/graph_update"]
    meta: default_meta
    coupling: default_coupling

yolo_module:
  ros__parameters:
    core: yolo_core
    afferent: yolo_afferent
    yolo_afferent:
      topics: ["/astra/color/image_raw"]
      type: sensor_msgs/msg/Image
    efferent: yolo_efferent
    yolo_efferent:
      topics: ["/coresense_detections"]
      type: yolov8_msgs/msg/DetectionArray
    meta: default_meta
    coupling: default_coupling